### ISSUE TITLE
rename CONTRIBUTOR GUIDELINES.md

### ISSUE THREAD

**Issue by acabunoc** [JoPauls/OpenHeart-Project#8]
HI @JoPauls!

Great work on your repo. One change I'd recommend is renaming `CONTRIBUTOR GUIDELINES.md` to `CONTRIBUTING.md`. This way, github knows you have contributor guidelines and will point newcomers to that automagically 😃

**Comment by JoPauls** [comment]
Hey Abigail,

thanks for the tip.
Made the change.

Cheers
Jo
